# Generated by Django 3.2.5 on 2022-04-07 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0002_auto_20220407_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Телефон должен быть введен в формате 7XXXXXXXXXX', regex='/^7[0-9]{10}/')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='utc',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Часовой пояс вводится в формате UTC-X или UTC-XX', regex='/UTC[+?-][0-9]{1,2}/')]),
        ),
    ]
