# Generated by Django 3.2.5 on 2022-04-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0005_alter_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
