# Generated by Django 3.2.5 on 2022-04-08 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0006_auto_20220408_0209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': ('Клиент',), 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': ('Сообщение',), 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': ('Рассылка',), 'verbose_name_plural': 'Рассылки'},
        ),
    ]
