version: '3'
services:
  redis:
    image: redis
    restart: always
    container_name: 'notification_redis'
    command: redis-server
    ports:
      - '6379:6379'
  web:
    build: .
    image: notification_service_web
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - SECRET_KEY=foo
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - API_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODA2MDg1ODYsImlzcyI6ImZhYnJpcXVlIiwibmFtZSI6IlN3YWVhbWkifQ.qg14tI8ZTKp41NqNETST9cautCCp6WsKgsizX6v-FAc
  web_makemigrations:
    extends:
      service: web
    command: python manage.py makemigrations
  web_migrate:
    extends:
      service: web
    command: python manage.py migrate
    depends_on:
      - web_makemigrations
  web_run:
    extends:
      service: web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - web_migrate
  celery:
    extends:
      service: web
    image: notification_service_celery
    command: celery -A notification_service worker -P gevent --loglevel=INFO -E
    links:
      - redis
    depends_on:
      - web_run
      - redis
